project_dir: /home/ehre/Documents/Projects/footballProject
save_dir: /home/ehre/Documents/Projects/footballProject/logs

feature_config:
  loading: ['game_id','play_id', 'nfl_id', 'frame_id']
  model:
    norm:  ['absolute_yardline_number', 'player_height', 'player_weight', 'x', 'y', 's', 'a', 'dir', 'o']
    no_norm: ['player_to_predict', 'play_direction', 'player_position', 'player_side']
  used: ${add_3:${feature_config.loading}, ${feature_config.model.norm}, ${feature_config.model.no_norm}}
  not_used: ['player_name', 'num_frames_output', 'ball_land_x', 'ball_land_y']
  
data:
  data_type: graph # sequential
  dataset: 
    data_dir: ${project_dir}/data/nfl-big-data-bowl-2026-prediction/train_test
    scaling_path: ${project_dir}/conf/updated_min_max_values.yaml    
    pos_path: ${project_dir}/data/positions/positions.txt  
  dataloading: 
    num_workers: 0
    persistent_workers: True 

model: 
  frame_embedding: add
  norm_length: ${len:${feature_config.model.norm}}
  no_norm_length: ${len:${feature_config.model.no_norm}}
  token_factor: 0.25
  players: 17 
  features: ${add_2:${model.norm_length}, ${model.no_norm_length}} 
  batch: ${data.dataloading.batch_size}
  optimizer: 
    lr: 0.0001
    # betas: [0.9, 0.999]
  lr_scheduler: 
    T_max: 5
    eta_min: 0.01
  transformer: 
    d_model: 13
    nhead: 1
    dim_feedforward: 13
  pos: 
    hidden_dim_1: 13 
    hidden_dim_2: 64
    output_dim: ${model.features}
  i:   
    input_dim: ${model.features}
    hidden_dim: 64
    output_dim: 13
  graph:
    in_channels: ${model.features} # Numbber of features
    hidden_channels: 20 
    num_layers: 10 
    out_channels: 13

logger: 
  name: NFLogger
  save_dir: ${save_dir}/logger
  version: "graph_medium_all_data"
  project: GetRichOrDieTrying
  log_model: all 
  checkpoint_name: checkpoint_logger

modelCheckpoint: 
  dirpath: ${save_dir}/checkpoint_model 
  filename: WhatAModelTheBestModelEverybodySaysThat
  monitor: val_loss
  save_top_k: 1 
  mode: min

profiler: 
  dirpath: ${save_dir}/profiler

trainer:  
  max_epochs: 100
  log_every_n_steps: 5
  limit_predict_batches: 1 


